### ISSUE TITLE
TODO Refacto

### ISSUE THREAD

**Issue by Airdoggo** [DigitalHolography/Holovibes#13]
All the refactoring issues the 2021 interns have spotted so far.
This will eventually turn into multiple individual issues.

- [x] Chrono wrapper not used everywhere where chrono library is used
- [x] Dictionary instead of "else if"
https://github.com/DigitalHolography/Holovibes/blob/e82a8e47def0cf333c4790c25e5d96368cabf664/Holovibes/sources/core/holovibes.cc#L87-L102
- [x] Needs a ! after the start of the comment
https://github.com/DigitalHolography/Holovibes/blob/e82a8e47def0cf333c4790c25e5d96368cabf664/Holovibes/includes/core/holovibes.hh#L129
- [x] There is no end to the "\name Getters/Setters" doxygen tag in holovibes.hh 
https://github.com/DigitalHolography/Holovibes/blob/e82a8e47def0cf333c4790c25e5d96368cabf664/Holovibes/includes/core/holovibes.hh#L102
- [x] Update documentation with the new header
https://github.com/DigitalHolography/Holovibes/blob/e82a8e47def0cf333c4790c25e5d96368cabf664/Holovibes/includes/io_files/holo_file.hh#L13-L24
https://github.com/DigitalHolography/Holovibes/blob/master/docs/Holo%20file%20format.md#18-bytes-binary-header
- [x] Normalize nested namespace with :: instead of {}
- [x] Normalize comment format
- [x] Normalize variable names
- [x] Add a "\file" doxygen tag to every header file
