### ISSUE TITLE
Add tests

### ISSUE THREAD

**Issue by noTban** [DigitalHolography/Holovibes#355]
Several tests need to be added to the testsuite.

- [ ] For tests that should fail retrieve the error message/log ad put it in the _error.txt_. For now, only the error code is given.
- [ ] Add tests with spatial and/or temporal transformations on non-square images. Before building references, ask Michael for a real anamorphic input, and see with him if the transformations have the correct behavior. https://github.com/DigitalHolography/Holovibes/issues/40#issue-992155940
- [ ] Add corresponding inputs for the bad header/footer/bytecode/bigendian tests
- [ ] Add cli arguments for the raw_double test
- [ ] Add a test with incorrect compute settings (the expected behavior in gui is to adopt default compute settings, but to abort in cli)
- [ ] Add a test with incorrect cli arguments
- [ ] Add tests for Hologram record https://github.com/DigitalHolography/Holovibes/issues/337#issue-2016588351
- [ ] Add tests for Chart record https://github.com/DigitalHolography/Holovibes/issues/337#issue-2016588351
- [ ] Add tests for Cuts record https://github.com/DigitalHolography/Holovibes/issues/256#issue-1087092030 https://github.com/DigitalHolography/Holovibes/issues/337#issue-2016588351
- [ ] Add tests with .cine input https://github.com/DigitalHolography/Holovibes/issues/258#issue-1087093901
- [ ] Add tests with input having 8 and 16 bit per pixel

For each of these tests, check by hand and with the help of Michael when needed if the result is what is expected, and only build ref if they are. Each time you finish adding a test that is already linked to an issue, close the corresponding issue.

**Comment by NoeTopeza** [comment]
Vérification du bon fonctionnement des charts, ajout de leur records depuis la CLI puis création de test de non regression par comparaison de charts en cours
