### ISSUE TITLE
Release 13.0.0

### ISSUE THREAD

**Issue by noTban** [DigitalHolography/Holovibes#362]
Quite a lot of labs are buying cameras, grabbers and computers in order to run Holovibes.
We need to release a stable, efficient and well documented version.

The main things to do are :

- [x] Change the CPU mode to activate only when recording (https://github.com/DigitalHolography/Holovibes/issues/361#issue-2197598909)
- [x] Finish the addition of regression tests (https://github.com/DigitalHolography/Holovibes/issues/355#issue-2184272294), and **thoroughly** test the program
- [x] Fix Adimek cameras (https://github.com/DigitalHolography/Holovibes/issues/360#issue-2197589021)
- [x] Test the cameras, and ensure **s711** works perfectly
- [x] Fix the record on GUI (https://github.com/DigitalHolography/Holovibes/issues/345#issue-2127292543, https://github.com/DigitalHolography/Holovibes/issues/359#issue-2197559432)
- [x] Fix the user settings crash (https://github.com/DigitalHolography/Holovibes/issues/366#issue-2213442478)
- [x] Fix the compute settings crash
- [x] Fix the raw mode bug (https://github.com/DigitalHolography/Holovibes/issues/379#issue-2258933881)
- [x] Fix the 3D cuts crash (https://github.com/DigitalHolography/Holovibes/issues/385#issue-2271036386)
- [x] Add a restrained mode settable in the advanced settings when opening with camera, with only the record options (#388)
- [x] Fix record crashes (https://github.com/DigitalHolography/Holovibes/issues/412#issue-2327818878) (https://github.com/DigitalHolography/Holovibes/issues/411#issue-2327805220)
- [x] Update the documentation

**Comment by NoeTopeza** [comment]
v13.0 released
